baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "nope"

[menu]
  [[menu.header]]
    name = "Article"
    url = "/article/"
    weight = 1
  [[menu.header]]
    name = "Video"
    url = "/video/"
    weight = 2
  [[menu.header]]
    name = "Tags"
    url = "/tag/"
    weight = 3
  [[menu.header]]
    name = "Guide"
    url = "/guide"
    weight = 4
  [[menu.header]]
    name = "Book"
    url = "/book/"
    weight = 5